### PR TITLE
Implement SignMessage for Trezor and Ledger hardware wallets

### PR DESCRIPTION
**Pull request by kanzure**
Here's are some Interaction classes for calling `signmessage` on these two hardware wallet devices.

### CODE REVIEW

**Review by humanumbrella — COMMENTED** [review]
Sweet - thanks for adding.

Code LGTM -- you able to add any unit test coverage?

**Comment by kanzure** [comment]
Maybe the real test was in our hearts all along? Actually, I am not familiar with the unit tests for unchained-wallets. Maybe I could get a brief overview of how these work or what exactly the tests are testing?

**Comment by kanzure** [comment]
ping @humanumbrella; or can we get this in without the new tests?

**Comment by kanzure** [comment]
Coverage should be better now. Looks good?

**Comment by steveblackmon** [comment]
tests passed for me 👍

**Comment by kanzure** [comment]
Thank you

**Pull request merged**
